site_name: 信息科学学习笔记
site_author: WU,Junchao

repo_name: IS-Learning-Notes
repo_url: https://github.com/junchaoIU/IS-Learning-Notes/

copyright: Copyright &copy; 2022-present <a href="https://github.com/junchaoIU" target="_blank" rel="noopener noreferrer">WU,Junchao</a>


theme:
  name: material
  language: zh
  include_search_page: false
  search_index_only: true

  features:
      - header.autohide
      # - navigation.instant
      # - navigation.expand
      # - navigation.sections
      - navigation.tracking
      # - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      # - navigation.indexes
      - search.highlight
      - search.share
      - search.suggest
      # - toc.integrate
      - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/junchaoIU/IS-Learning-Notes/

nav:
  - 前言: "index.md"
  - How to Research:
      - 文献查询与阅读: "How to Research/文献查询与阅读/文献查询与阅读.md"
      - 论文写作: "How to Research/论文写作/论文写作.md"
      - 分享研究: "How to Research/分享研究/分享研究.md"
  - 学术论文技巧:
      - 学术论文分类: "学术论文相关/学术论文分类/学术论文分类.md"
      - 学术论文写作:
          - "Cover Letter": "学术论文相关/学术论文写作/Cover Letter/Cover Letter.md"
          - "Revising": "学术论文相关/学术论文写作/Revising/Revising.md"
  - 自然语言处理:
      - 中文NLP研究与资源汇总: "自然语言处理/中文NLP研究与资源汇总/中文NLP研究与资源汇总.md"
      - NLP概述: "自然语言处理/NLP概述/NLP概述.md"
      - 中文分词技术: "自然语言处理/中文分词技术/中文分词技术.md"
      - 命名实体识别: "自然语言处理/命名实体识别/命名实体识别.md"
      - 关系抽取: "自然语言处理/关系抽取/关系抽取.md"
      - 词性标注: "自然语言处理/词性标注/词性标注.md"
      - 文本向量化: "自然语言处理/文本向量化/文本向量化.md"
      - 句法分析: "自然语言处理/句法分析/句法分析.md"
      - 情感分析: "自然语言处理/情感分析/情感分析.md"
      - 信息抽取: "自然语言处理/信息抽取/信息抽取.md"
      - 文本聚类: "自然语言处理/文本聚类/文本聚类.md"
      - 文本分类: "自然语言处理/文本分类/文本分类.md"
      - 事件抽取: "自然语言处理/事件抽取/事件抽取.md"
  - 统计机器学习:
      - K近邻: "统计机器学习/K近邻/K近邻.md"
      - 决策树: "统计机器学习/决策树/决策树.md"
      - 神经网络: "统计机器学习/神经网络/神经网络.md"
      - 降维与度量学习: "统计机器学习/降维与度量学习/降维与度量学习.md"
      - 无监督学习概论: "统计机器学习/无监督学习概论/无监督学习概论.md"
      - PageRank算法: "统计机器学习/PageRank算法/PageRank算法.md"
  - 深度学习算法:
      - BERT: "深度学习算法/BERT/BERT.md"
      - LSTM: "深度学习算法/LSTM/LSTM.md"
      - RNNs: "深度学习算法/RNNs/RNNs.md"
      - CNN: "深度学习算法/CNN/CNN.md"
      - Transformer: "深度学习算法/Transformer/Transformer.md"
  - 知识图谱技术:
      - 知识图谱概述: "知识图谱技术/知识图谱概述/知识图谱概述.md"
      - 知识表示: "知识图谱技术/知识表示/知识表示.md"
      - 知识建模: "知识图谱技术/知识建模/知识建模.md"
      - 知识抽取: "知识图谱技术/知识抽取/知识抽取.md"
      - 知识融合: "知识图谱技术/知识融合/知识融合.md"
      - 知识表示学习: "知识图谱技术/知识表示学习/知识表示学习.md"
      - 知识存储: "知识图谱技术/知识存储/知识存储.md"
      - 知识推理: "知识图谱技术/知识推理/知识推理.md"
      - 多模态知识图谱概述: "知识图谱技术/多模态知识图谱概述/多模态知识图谱概述.md"
  - 机器翻译:
      - 机器翻译概述: "机器翻译/机器翻译概述.md"
      - 非自回归模型机器翻译: "机器翻译/非自回归模型机器翻译.md"
      - RNN神经机器翻译: "机器翻译/RNN神经机器翻译.md"
      - CNN神经机器翻译: "机器翻译/CNN神经机器翻译.md"
      - Transformer神经机器翻译: "机器翻译/Transformer神经机器翻译.md"
      - 无监督机器翻译: "机器翻译/无监督机器翻译.md"
      - 多语言机器翻译: "机器翻译/多语言机器翻译.md"
      - 多模态机器翻译: "机器翻译/多模态机器翻译.md"
      - 篇章机器翻译: "机器翻译/篇章机器翻译.md"
      - 领域自适应: "机器翻译/领域自适应.md"
      - 知识图谱增强的机器翻译: "机器翻译/知识图谱增强的机器翻译.md"
      - mBART: "机器翻译/mBART：Multilingual Denoising Pre-training for Neural Machine Translation.md"
  - 立场检测研究:
      - 立场检测笔记: "立场检测研究/立场检测研究.md"
      - 数据集:
          - "NLPCC2016-Task4": "立场检测研究/NLPCC2016-Task4/NLPCC2016-Task4.md"